### ISSUE TITLE
Couldn't get digest: digest not found in []

### ISSUE THREAD

**Issue by i4specete** [aquasecurity/manifesto#5]
Error:

./manifesto put hello-world:latest test test.json 

Couldn't get digest: digest not found in []

**Comment by lizrice** [comment]
Hi @i4specete, I think the problem is that you're trying to add data to an image repo that you don't own in the registry. You'd need to do something like this to create your own version of the repo: 

```
docker tag hello-world:latest <yourname>/hello-world:latest 
docker push <yourname>/hello-world:latest 
```
Then you should be able to do 

```
./manifesto put <yourname>/hello-world:latest test test.json
```

**Comment by i4specete** [comment]
Hi, 

I tried you said me but the error persists...

To replicate the error:

docker pull hello-world
docker tag hello-world pecete/hello-world
./manifesto put pecete/hello-world:latest  test test.json

Error:

Storing metadata 'test' for 'pecete/hello-world:latest'
Couldn't get digest: digest not found in []

Regards

**Comment by i4specete** [comment]
Another error is that when you put ":" in the repo name the tool split that beacuse the tool think that is the tag.

localhost:5000/

**Comment by viccab** [comment]
You will need to login to the Hub registry first using,
    docker login -u <yourname> -p <password> 
and run,
    docker push <yourname>/hello-world:latest
Then you should be able to do, 
    ./manifesto put <yourname>/hello-world:latest test test.json

**Comment by lizrice** [comment]
Thanks for that - the login is a good point (I'll add that to the readme now) and we should also parse the repo name better.

**Comment by lizrice** [comment]
Registry name issue now covered by #9, I think everything else in this issue is dealt with so I'm closing. Please comment or raise new issues if I missed something.
